import { ShopItem } from '../types/shop';
import { CharacterProfile, BossEntity } from '../types/character';
import { Quest } from '../types/quest';

export const INITIAL_SHOP_ITEMS: ShopItem[] = [
  // Weapons
  {
    id: 'wpn-1',
    name: 'Code-Forged Mechanical Keyboard',
    description: 'Forged from aircraft-grade aluminum and blue clicky switches. Sharpens deep coding sessions.',
    category: 'weapon',
    rarity: 'rare',
    costGold: 120,
    costGems: 0,
    icon: '⌨️',
    modifier: {
      xpBonusPercent: 15,
      attributeBoost: { attribute: 'intellect', multiplier: 1.25 },
    },
    requiredLevel: 2,
  },
  {
    id: 'wpn-2',
    name: "Titan's Hex Dumbbells",
    description: 'Forged from stellar iron. Boosts muscle growth and strength conditioning.',
    category: 'weapon',
    rarity: 'rare',
    costGold: 110,
    costGems: 0,
    icon: '🏋️‍♂️',
    modifier: {
      xpBonusPercent: 15,
      attributeBoost: { attribute: 'strength', multiplier: 1.25 },
    },
    requiredLevel: 2,
  },
  {
    id: 'wpn-3',
    name: 'Chronos Hyper-Watch',
    description: 'Manipulates time perception. Accelerates task completion speed and chore execution.',
    category: 'weapon',
    rarity: 'epic',
    costGold: 220,
    costGems: 2,
    icon: '⏱️',
    modifier: {
      xpBonusPercent: 20,
      attributeBoost: { attribute: 'agility', multiplier: 1.3 },
    },
    requiredLevel: 4,
  },
  {
    id: 'wpn-4',
    name: 'Blade of Unbroken Will',
    description: 'A legendary crystalline blade that radiates relentless momentum and supreme discipline.',
    category: 'weapon',
    rarity: 'legendary',
    costGold: 500,
    costGems: 10,
    icon: '🗡️',
    modifier: {
      xpBonusPercent: 35,
      goldBonusPercent: 25,
      hpBonus: 100,
    },
    requiredLevel: 7,
  },

  // Armor & Gear
  {
    id: 'arm-1',
    name: 'Cloak of Restful Slumber',
    description: 'Woven with moonlit thread. Enhances deep restorative sleep, recovery, and hydration.',
    category: 'armor',
    rarity: 'rare',
    costGold: 95,
    costGems: 0,
    icon: '🧥',
    modifier: {
      attributeBoost: { attribute: 'vitality', multiplier: 1.25 },
      hpBonus: 50,
    },
    requiredLevel: 1,
  },
  {
    id: 'arm-2',
    name: 'Cyber-Optic HUD Visor',
    description: 'Overlay interface highlighting distractions in red and critical objectives in golden neon.',
    category: 'armor',
    rarity: 'epic',
    costGold: 260,
    costGems: 3,
    icon: '🥽',
    modifier: {
      xpBonusPercent: 25,
      attributeBoost: { attribute: 'intellect', multiplier: 1.35 },
    },
    requiredLevel: 4,
  },
  {
    id: 'arm-3',
    name: "Emperor's Charisma Tuxedo",
    description: 'Tailored with silver weaves. Inspires awe in meetings, conversations, and social arenas.',
    category: 'armor',
    rarity: 'rare',
    costGold: 140,
    costGems: 0,
    icon: '👔',
    modifier: {
      attributeBoost: { attribute: 'charisma', multiplier: 1.3 },
    },
    requiredLevel: 3,
  },

  // Potions & Consumables
  {
    id: 'pot-1',
    name: 'Elixir of Hyper-Focus (2x XP)',
    description: 'Double XP reward on your next completed quest. Brewed with matcha and lion’s mane.',
    category: 'potion',
    rarity: 'common',
    costGold: 45,
    costGems: 0,
    icon: '🧪',
    modifier: {
      xpBonusPercent: 100,
    },
    requiredLevel: 1,
  },
  {
    id: 'pot-2',
    name: 'Aegis Streak Freeze Shield',
    description: 'Ancient protective rune. Automatically prevents your consecutive streak from resetting if you miss a day.',
    category: 'potion',
    rarity: 'rare',
    costGold: 80,
    costGems: 1,
    icon: '🛡️',
    modifier: {
      streakShield: true,
    },
    requiredLevel: 1,
  },
  {
    id: 'pot-3',
    name: 'Phoenix Heart Elixir',
    description: 'Instantly replenishes 100% of your maximum Health (HP) and Mana.',
    category: 'potion',
    rarity: 'common',
    costGold: 35,
    costGems: 0,
    icon: '❤️‍🔥',
    modifier: {
      hpBonus: 100,
    },
    requiredLevel: 1,
  },

  // Badges & Titles
  {
    id: 'bdg-1',
    name: 'Title: The Relentless Vanguard',
    description: 'Prestige title displayed beneath your avatar indicating iron discipline.',
    category: 'badge',
    rarity: 'epic',
    costGold: 180,
    costGems: 2,
    icon: '🎖️',
    modifier: {
      goldBonusPercent: 10,
    },
    requiredLevel: 5,
  },
];

export const INITIAL_CHARACTER: CharacterProfile = {
  id: 'char-hero-1',
  userId: 'user-demo-1',
  name: 'Kaelen Vance',
  title: 'Novice Adventurer',
  bio: 'Turning mundane days into legend. Leveling code, iron, and mind.',
  characterClass: 'technomancer',
  avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
  level: 3,
  currentXp: 180,
  maxXp: 520, // calculated from formula
  hp: 85,
  maxHp: 100,
  mana: 60,
  maxMana: 100,
  gold: 145,
  gems: 4,
  streak: 5,
  longestStreak: 12,
  streakShieldActive: true,
  lastActiveDate: new Date().toISOString().split('T')[0],
  streakHistory: [
    new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
    new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    new Date().toISOString().split('T')[0],
  ],
  attributes: {
    strength: { level: 2, currentXp: 40, maxXp: 120, tasksCompleted: 4 },
    intellect: { level: 4, currentXp: 95, maxXp: 200, tasksCompleted: 9 },
    vitality: { level: 2, currentXp: 70, maxXp: 120, tasksCompleted: 5 },
    agility: { level: 1, currentXp: 30, maxXp: 80, tasksCompleted: 2 },
    charisma: { level: 2, currentXp: 20, maxXp: 120, tasksCompleted: 3 },
  },
  equippedGear: {
    weaponId: 'wpn-1',
    armorId: 'arm-1',
  },
  unlockedBadges: ['badge_first_quest', 'badge_streak_3', 'badge_level_3'],
};

export const INITIAL_BOSS: BossEntity = {
  id: 'boss-procrastination-1',
  name: 'The Procrastination Behemoth',
  title: 'Devourer of Stolen Hours & Unwritten Futures',
  currentHp: 460,
  maxHp: 1000,
  level: 5,
  avatarUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&auto=format&fit=crop&q=80',
  description: 'Feeds on skipped gym sessions, postponed commits, and endless social media scrolling. Strikes on every completed quest!',
  rewardGold: 350,
  rewardXp: 400,
  rewardBadge: 'Slayer of Delay',
  defeated: false,
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest-1',
    userId: 'user-demo-1',
    title: 'Complete 90-Minute Deep Work / Coding Session',
    description: 'Build core frontend modules without switching tabs or looking at notifications.',
    attribute: 'intellect',
    difficulty: 'hard',
    type: 'todo',
    status: 'active',
    priority: 'high',
    xpReward: 90,
    goldReward: 40,
    dueDate: new Date().toISOString().split('T')[0],
    createdAt: new Date().toISOString(),
    tags: ['Coding', 'Deep Work'],
  },
  {
    id: 'quest-2',
    userId: 'user-demo-1',
    title: 'Morning Pushup & Core Conditioning (100 Reps)',
    description: 'Set of pushups, planks, and bodyweight squats to kickstart metabolic energy.',
    attribute: 'strength',
    difficulty: 'medium',
    type: 'habit',
    status: 'active',
    priority: 'medium',
    xpReward: 50,
    goldReward: 20,
    streakCount: 5,
    dueDate: new Date().toISOString().split('T')[0],
    createdAt: new Date().toISOString(),
    tags: ['Fitness', 'Morning'],
  },
  {
    id: 'quest-3',
    userId: 'user-demo-1',
    title: 'Hydration Challenge: Drink 3L Filtered Water',
    description: 'Maintain cellular hydration and cognitive acuity throughout the day.',
    attribute: 'vitality',
    difficulty: 'easy',
    type: 'habit',
    status: 'active',
    priority: 'low',
    xpReward: 25,
    goldReward: 10,
    streakCount: 7,
    dueDate: new Date().toISOString().split('T')[0],
    createdAt: new Date().toISOString(),
    tags: ['Health', 'Habit'],
  },
  {
    id: 'quest-4',
    userId: 'user-demo-1',
    title: 'Clear Inbox & Organize Desktop Workspace',
    description: 'Archive stale emails, organize project folders, and wipe desk clear.',
    attribute: 'agility',
    difficulty: 'easy',
    type: 'todo',
    status: 'active',
    priority: 'medium',
    xpReward: 30,
    goldReward: 15,
    createdAt: new Date().toISOString(),
    tags: ['Chores', 'Organization'],
  },
  {
    id: 'quest-5',
    userId: 'user-demo-1',
    title: 'Reach out to 2 Mentors or Industry Peers',
    description: 'Send thoughtful updates and foster high-value professional relationships.',
    attribute: 'charisma',
    difficulty: 'medium',
    type: 'todo',
    status: 'active',
    priority: 'high',
    xpReward: 60,
    goldReward: 25,
    createdAt: new Date().toISOString(),
    tags: ['Networking', 'Career'],
  },
  {
    id: 'quest-6',
    userId: 'user-demo-1',
    title: 'Finish Reading 20 Pages of System Design Book',
    description: 'Deepen knowledge on distributed architectures and latency optimization.',
    attribute: 'intellect',
    difficulty: 'medium',
    type: 'habit',
    status: 'completed',
    priority: 'medium',
    xpReward: 45,
    goldReward: 18,
    completedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    tags: ['Reading', 'Intellect'],
  },
];
